### ISSUE TITLE
Komponent: use released version instead of Git

### ISSUE THREAD

**Issue by Spone** [damienlethiec/modern-rails-template#12]
Hi there,

I think you should use the latest released version instead of pointing to Github:

https://github.com/damienlethiec/modern-rails-template/blob/d6acb0cb0ec8e5dfa60da9faa0adec8d0cb91446/template.rb#L111

**Comment by damienlethiec** [comment]
Indead @Spone, this was the case at the beginning but I had problems with the Stimulus config in the latest released version. Only the one pointing to Github gave make the correct config in `stimulus.js`.

**Comment by Spone** [comment]
Yeah, support for Stimulus 1.0 will be shipped with the next release.

**Comment by damienlethiec** [comment]
Perfect! I will refer to the latest release when it is done :) Thanks for the great work!

**Comment by florentferry** [comment]
We released a `1.1.2` version available on rubygems with Stimulus 1.0

**Comment by damienlethiec** [comment]
Great!! Thanks!! I will update the template this week-end :)

**Comment by damienlethiec** [comment]
Done:
https://github.com/damienlethiec/modern-rails-template/commit/e8ab1fb3696d465f443b61a95395315f679f5526
